### ISSUE TITLE
Current code running on windows reports multiple errors

### ISSUE THREAD

**Issue by htung0101** [neuroailab/tdw_physics#54]
I am trying to generate data on the window machines, but I get several errors.
Can someone make sure that the code can run on winodws? Here are some of the errors:

1) stopit is not working on window. @felixbinder  

Traceback (most recent call last):
  File "tdw_physics/target_controllers/dominoes.py", line 1759, in <module>
    args_dict=vars(args))
  File "c:\cygwin64\home\hsiaoyut\2021\tdw_physics\tdw_physics\dataset.py", line 236, in run
    with stopit.SignalTimeout(5) as to_ctx_mgr: #since TDW sometimes doesn't acknowledge being stopped we only *try* to close it
  File "C:\cygwin64\home\hsiaoyut\anaconda\envs\tdw\lib\site-packages\stopit\utils.py", line 73, in __enter__
    self.setup_interrupt()
  File "C:\cygwin64\home\hsiaoyut\anaconda\envs\tdw\lib\site-packages\stopit\signalstop.py", line 33, in setup_interrupt
    signal.signal(signal.SIGALRM, self.handle_timeout)
AttributeError: module 'signal' has no attribute 'SIGALRM'

2) things that try to use subprocess run is not working (not sure if related to cygwin)
  File "c:\cygwin64\home\hsiaoyut\2021\tdw_physics\tdw_physics\dataset.py", line 545, in _write_static_data
    res = subprocess.run('git rev-parse HEAD', shell=True, capture_output=True, text=True)
  File "C:\cygwin64\home\hsiaoyut\anaconda\envs\tdw\lib\subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

3) related to 2, deleting png with subprocess is not working:

rm: cannot remove 'datadominoespilot_dominoes_1mid_J025R45_boxroompngs_0002/img_*.png': No such file or directory
ipdb> self.png_dir

4) save movie also uses subprocess, and it is not working 
                        cmd, stdout, stderr = pngs_to_mp4(
                            filename=mp4_filename,
                            image_stem=pass_mask[1:]+'_',
                            png_dir=self.png_dir,
                            size=[self._height, self._width],
                            overwrite=True,
                            remove_pngs=True,
                            use_parent_dir=False)

**Comment by felixbinder** [comment]
https://github.com/neuroailab/tdw_physics/commit/e768a97b2a8c79062bad6180c9b1a0e7ae6072b0 Fixes your first issue—looks like Windows doesn't support ending processes with signals 🤬 You could try to replace `stopit.SignalTimeout(5)` with `stopit.ThreadingTimeout(5)` and see if that works. Now it'll hang on Windows again

**Comment by felixbinder** [comment]
Don't know about the second one—I think that has always been the case and we've been ignoring the pngs. Not sure about the movie

**Comment by htung0101** [comment]
@danielbear : Can you check 2, 3, 4? Can we assign someone to fix this in the master branch?
Basically to make sure the current thing can run on Windows.

**Comment by danielbear** [comment]
A. can you see if these errors appear when you are not saving passes or saving movies?

B. Do you need to generate PNGs or MP4s on Windows, or just the HDF5?

C. are these errors occurring on all Windows machines or just the Windows render node on our cluster? It seemed the others rendering on different Windows machines were not seeing these errors.

**Comment by danielbear** [comment]
If you don’t need the PNGs or MP4s then subprocess.run should not be necessary; even if you do, they can be generated from the HDF5s after the fact. This sounds like an issue specific to the Windows node on our cluster, though, since I think @choldawa and @arty-p have both been rendering on their own Windows machines without issue.

**Comment by danielbear** [comment]
Any update on this? Are you still unable to render on Windows when you exclude the suprocess.run calls?
